[package]
name = "codingame_rs"
version = "0.1.0"
authors = ["Wojciech Nawa <wojciech.nawa@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
itertools = "0.8.0"
libc = "0.2.50"
rand = "0.6.5"
regex = "1.1.0"
time = "0.1.42"
